### ISSUE TITLE
Broken NFC

### ISSUE THREAD

**Issue by Morozko122** [SamarV-121/android_device_realme_RMX2001#3]
Hi. I have realme 6 with nfc and this is not the first time I've encountered this problem. (NFC also doesn't work for others a11 based custom rom)I attach a log file. [log](https://del.dog/vywohapuna) I hope you and your team can fix this bug.

**Comment by SamarV-121** [comment]
@Morozko122 kul

**Comment by SamarV-121** [comment]
@SamarV-121 tf

**Comment by SamarV-121** [comment]
@Morozko122 check in this build 
https://github.com/SamarV-121/releases/releases/download/20210115_190206/lineage-18.1-20210115_181509-UNOFFICIAL-2f5352f-RMX2001.zip

**Comment by Morozko122** [comment]
Hi. I checked on nfc tag and it works. Tomorrow I'll go to the store near my house and check Google Pay.

**Comment by SamarV-121** [comment]
@Morozko122 it is working?

**Comment by Morozko122** [comment]
Yes. Thanks a lot.

**Comment by SamarV-121** [comment]
@Morozko122 can you confirm NFC is working or not on this one 
https://samarv-121.github.io/lineageos-18.1-RMX2001/ | https://github.com/SamarV-121/releases/releases/download/20210117_170301/lineage-18.1-20210117_162055-UNOFFICIAL-45d5a15-RMX2001.zip

**Comment by Morozko122** [comment]
Yes of course

**Comment by SamarV-121** [comment]
@Morozko122 OK
